import Head from "next/head";
import Link from "next/link";
import { useMoralis } from "react-moralis";
import styles from "../styles/Layout.module.css";

function Layout({ children }) {
  // MORALIS
  const { isWeb3Enabled, enableWeb3 } = useMoralis();

  return (
    <>
      <Head>
        <title>Cross Save</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />

        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins&family=Space+Grotesk&display=swap"
          rel="stylesheet"
        />
      </Head>
      <nav className={styles.nav}>
        <Link href="/">
          <img src="/logo.png" />
        </Link>

        <div>
          {isWeb3Enabled && (
            <Link href="/dashboard" className={styles.button1}>
              My DashBoard
            </Link>
          )}
          <button className={styles.button2} onClick={enableWeb3}>
            {isWeb3Enabled ? "Connected" : "Connect"}
          </button>
        </div>
      </nav>
      <div>{children}</div>
    </>
  );
}

export default Layout;
